# Generated by Django 3.1.7 on 2021-04-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registered_users',
            name='User_Name',
            field=models.CharField(max_length=30),
        ),
    ]
